apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: klogo
  labels:
    # serving.knative.dev/visibility: cluster-local
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/knative-samples/klogo:latest
            env:
            - name: RELEASE
              value: "v0.0.5"
            - name: GIN_MODE
              value: "release"